ClientManagerApplication/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientManagerApplication.Controllers
{
    public class AddressController : Controller
    {
        Models.ClientsEntities database = new Models.ClientsEntities();

        // GET: Address
        public ActionResult Index(int id)//Person ID
        {
            ViewBag.id = id;

            Models.Person thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            return View(thePerson);
        }

        // GET: Address/Details/5
        public ActionResult Details(int id)//Address ID
        {
            Models.Address theAddress = database.Addresses.SingleOrDefault(c => c.address_id == id);
            return View(theAddress);
        }

        // GET: Address/Create
        public ActionResult Create(int id)//Person ID
        {
            ViewBag.thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            ViewBag.countries = database.Countries.Select(c => new SelectListItem() { Value = c.country_code, Text = c.country_name });

            return View();
        }

        // POST: Address/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection)//Person ID
        {
          
            try
            {
                // TODO: Add insert logic here
                Models.Address newAddress = new Models.Address()
                {
                    city = collection["city"],
                    country_code = collection["country_code"],
                    description = collection["description"],
                    person_id = id,
                    province_state = collection["province_state"],
                    street = collection["street"],
                    zip_postal = collection["zip_postal"]
                };

                database.Addresses.Add(newAddress);
                database.SaveChanges();

                return RedirectToAction("Index", new { id = newAddress.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Address/Edit/5
        public ActionResult Edit(int id)//Address ID
        {
            Models.Address theAddress = database.Addresses.SingleOrDefault(c => c.address_id == id);
            ViewBag.countries = database.Countries.Select(c => new SelectListItem() { Value = c.country_code, Text = c.country_name });
            return View(theAddress);
        }

        // POST: Address/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)//Address ID
        {
            try
            {
                // TODO: Add update logic here
                Models.Address theAddress = database.Addresses.SingleOrDefault(c => c.address_id == id);

                    theAddress.city = collection["city"];
                    theAddress.country_code = collection["country_code"];
                    theAddress.description = collection["description"];
                    theAddress.province_state = collection["province_state"];
                    theAddress.street = collection["street"];
                    theAddress.zip_postal = collection["zip_postal"];
                

                database.SaveChanges();

                return RedirectToAction("Index", new { id = theAddress.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Address/Delete/5
        public ActionResult Delete(int id)//Address ID
        {
            Models.Address theAddress = database.Addresses.SingleOrDefault(c => c.address_id == id);
            return View(theAddress);
        }

        // POST: Address/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)//Address ID
        {
            try
            {
                // TODO: Add delete logic here
                Models.Address theAddress = database.Addresses.SingleOrDefault(c => c.address_id == id);
                database.Addresses.Remove(theAddress);
                database.SaveChanges();

                return RedirectToAction("Index", new { id = theAddress.person_id });
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientManagerApplication/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientManagerApplication.Controllers
{
    public class ContactController : Controller
    {

        Models.ClientsEntities database = new Models.ClientsEntities();

        // GET: Contact
        public ActionResult Index(int id)//Person ID
        {
            ViewBag.id = id;

            Models.Person thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            return View(thePerson);
        }

        // GET: Contact/Details/5
        public ActionResult Details(int id)//Contact ID
        {
            Models.Contact theContact = database.Contacts.SingleOrDefault(c => c.contact_id == id);
            return View(theContact);
        }

        // GET: Contact/Create
        public ActionResult Create(int id)//Person ID
        {
            ViewBag.thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            return View();
        }

        // POST: Contact/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection)//Person ID
        {
            try
            {
                // TODO: Add insert logic here
                Models.Contact newContact = new Models.Contact()
                {
                    person_id = id,
                    information_type = collection["information_type"],
                    information = collection["information"]
                };

                database.Contacts.Add(newContact);
                database.SaveChanges();

                return RedirectToAction("Index", new { id = newContact.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Edit/5
        public ActionResult Edit(int id)//Contact ID
        {
            var theContact = database.Contacts.SingleOrDefault(c => c.contact_id == id);
            return View(theContact);
        }

        // POST: Contact/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)//Contact ID
        {
            try
            {
                // TODO: Add update logic here
                Models.Contact theContact = database.Contacts.SingleOrDefault(c => c.contact_id == id);

                theContact.information_type = collection["information_type"];
                theContact.information = collection["information"];

                database.SaveChanges();

                return RedirectToAction("Index", new { id = theContact.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Delete/5
        public ActionResult Delete(int id)//Contact ID
        {
            Models.Contact theContact = database.Contacts.SingleOrDefault(c => c.contact_id == id);
            return View(theContact);
        }

        // POST: Contact/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)//Contact ID
        {
            try
            {
                // TODO: Add delete logic here
                Models.Contact theContact = database.Contacts.SingleOrDefault(c => c.contact_id == id);
                database.Contacts.Remove(theContact);
                database.SaveChanges();

                return RedirectToAction("Index", new { id = theContact.person_id });
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientManagerApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientManagerApplication.Controllers
{
    public class HomeController : Controller
    {

        Models.ClientsEntities database = new Models.ClientsEntities();

        // GET: Home
        public ActionResult Index()
        {
            return View(database.People);
        }

        public ActionResult Search(string name)
        {
            IEnumerable<Models.Person> result = database.People.Where(p => (p.first_name + " " + p.last_name).Contains(name));
            return View("Index", result);
        }

        // GET: Home/Details/5
        public ActionResult Details(int id)
        {
            Models.Person thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            return View(thePerson);
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                Models.Person newPerson = new Models.Person();

                newPerson.first_name = collection["first_name"];
                newPerson.last_name = collection["last_name"];
                newPerson.notes = collection["notes"];
                newPerson.gender = collection["gender"];

                database.People.Add(newPerson);
                database.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int id)
        {
            var thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            return View(thePerson);
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                Models.Person thePerson = database.People.SingleOrDefault(c => c.person_id == id);

                thePerson.first_name = collection["first_name"];
                thePerson.last_name = collection["last_name"];
                thePerson.notes = collection["notes"];
                thePerson.gender = collection["gender"];

                database.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int id)
        {
            Models.Person thePerson = database.People.SingleOrDefault(c => c.person_id == id);
            return View(thePerson);
        }

        // POST: Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.Person thePerson = database.People.SingleOrDefault(c => c.person_id == id);

                thePerson.picture_id = null;
                database.SaveChanges();

                database.Pictures.RemoveRange(thePerson.Pictures);
                database.Contacts.RemoveRange(thePerson.Contacts);
                database.Addresses.RemoveRange(thePerson.Addresses);
                database.SaveChanges();

                database.People.Remove(thePerson);
                database.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientManagerApplication/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientManagerApplication.Controllers
{
    public class PictureController : Controller
    {
        Models.ClientsEntities database = new Models.ClientsEntities();

        // GET: Picture
        public ActionResult Index(int id)//Person ID
        {
            Models.Person thePerson = database.People.SingleOrDefault(p => p.person_id == id);
            return View(thePerson);
        }

        // GET: Picture/Details/5
        public ActionResult Details(int id)//Picture ID
        {
            Models.Picture thePicture = database.Pictures.SingleOrDefault(p => p.picture_id == id);
            return View(thePicture);
        }

        // GET: Picture/Create
        public ActionResult Create(int id)//Person ID
        {
            ViewBag.thePerson = database.People.SingleOrDefault(p => p.person_id == id);
            return View();
        }

        // POST: Picture/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection, HttpPostedFileBase newPicture)//Person ID
        {
            try
            {
                // TODO: Add insert logic here
                string[] types = { "image/gif", "image/jpeg", "image/png" };

                if (newPicture != null
                    && newPicture.ContentLength > 0
                    && types.Contains(newPicture.ContentType))
                {
                    Guid g = Guid.NewGuid();
                    string filename = g.ToString() + Path.GetExtension(newPicture.FileName);
                    string path = Server.MapPath("~/Images/");
                    path = Path.Combine(path, filename);
                    newPicture.SaveAs(path);

                    Models.Picture newPic = new Models.Picture()
                    {
                        caption = collection["caption"],
                        location = collection["location"],
                        time = collection["time"],
                        path = filename,
                        person_id = id
                    };

                    database.Pictures.Add(newPic);
                    database.SaveChanges();
                }

                return RedirectToAction("Index", new { id = id });
            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult MakeMyProfile(int id)
        {
            Models.Picture thePicture = database.Pictures.SingleOrDefault(p => p.picture_id == id);
            thePicture.Person.picture_id = id;
            database.SaveChanges();
            return RedirectToAction("Index", new { id = thePicture.person_id });
        }

        // GET: Picture/Edit/5
        public ActionResult Edit(int id)//Picture ID
        {
            Models.Picture thePicture = database.Pictures.SingleOrDefault(p => p.picture_id == id);
            return View(thePicture);
        }

        // POST: Picture/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, HttpPostedFileBase thePicture)//Picture ID
        {
            try
            {
                // TODO: Add update logic here
                string[] types = { "image/gif", "image/jpeg", "image/png" };

                if (thePicture != null
                    && thePicture.ContentLength > 0
                    && types.Contains(thePicture.ContentType))               
                {
                    Guid g = Guid.NewGuid();
                    string filename = g.ToString() + Path.GetExtension(thePicture.FileName);
                    string path = Server.MapPath("~/Images/");
                    path = Path.Combine(path, filename);
                    thePicture.SaveAs(path);                            

                    Models.Picture aPicture = database.Pictures.SingleOrDefault(p => p.picture_id == id);

                    aPicture.caption = collection["caption"];
                    aPicture.time = collection["time"];
                    aPicture.location = collection["location"];
                    aPicture.path = filename;

                    database.SaveChanges();
                }

                return RedirectToAction("Index", new { id = id });
            }

            catch
            {
                return View();
            }
        }

        // GET: Picture/Delete/5
        public ActionResult Delete(int id)//Picture ID
        {
            Models.Picture thePicture = database.Pictures.SingleOrDefault(p => p.picture_id == id);
            return View(thePicture);
        }

        // POST: Picture/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)//Picture ID
        {
            try
            {
                // TODO: Add delete logic here
                Models.Picture thePicture = database.Pictures.SingleOrDefault(p => p.picture_id == id);
                database.Pictures.Remove(thePicture);
                database.SaveChanges();

                return RedirectToAction("Index", new { id = thePicture.person_id });
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientManagerApplication/Views/Home/Create.cshtml
@model ClientManagerApplication.Models.Person

@{
    ViewBag.Title = "Create";
}

<h3>Create a New Person Record</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClientManagerApplication/Views/Home/Delete.cshtml
@model ClientManagerApplication.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h3>
    Delete @Html.DisplayFor(model => model.first_name)
    @Html.DisplayFor(model => model.last_name)'s Record
</h3>

<h4>
    Are you sure you want to delete @Html.DisplayFor(model => model.first_name)
    @Html.DisplayFor(model => model.last_name)?
</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.picture_id)
        </dt>

        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.Picture.path)" style="max-height:100px; max-width:100px">
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClientManagerApplication/Views/Home/Details.cshtml
@model ClientManagerApplication.Models.Person

@{
    ViewBag.Title = "Details";
}

<h3>
    Details of @Html.DisplayFor(model => model.first_name)
    @Html.DisplayFor(model => model.last_name)'s Record
</h3>


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.picture_id)
        </dt>

        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.Picture.path)" style="max-height:100px; max-width:100px">
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.person_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClientManagerApplication/Views/Home/Edit.cshtml
@model ClientManagerApplication.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h3>
    Edit @Html.DisplayFor(model => model.first_name)
    @Html.DisplayFor(model => model.last_name)'s Record
</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.person_id)

        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClientManagerApplication/Views/Home/Index.cshtml
@model IEnumerable<ClientManagerApplication.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Home Page</h2>

<form method="get" action="/Home/Search">
    <label> Search: </label> <input type="text" name="name" /> <input type="submit" name="search" value="Search" class="btn btn-default" />
</form>

<p>
    @Html.ActionLink("Create New Profile", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.picture_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.first_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.last_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>
                <img src="/Images/@Html.DisplayFor(modelItem => item.Picture.path)" style="max-height:100px; max-width:100px">
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.first_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.last_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.ActionLink("Pictures", "Index", "Picture", new { id = item.person_id }, null) |
                @Html.ActionLink("Address Information", "Index", "Address", new { id = item.person_id }, null) |
                @Html.ActionLink("Contact Information", "Index", "Contact", new { id = item.person_id }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = item.person_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.person_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.person_id })
            </td>
        </tr>
    }

</table>